<%@ Page Language="C#" AutoEventWireup="true" CodeBehind="ManageUsers.aspx.cs" Inherits="IADProject10.ManageUsers" %>

<!DOCTYPE html>

<html xmlns="http://www.w3.org/1999/xhtml">
<head runat="server">
    <title>Manage Users</title>

    <style>

        body {
            font-family: Arial;
            margin: 30px;
            background-color: #f4f4f4;
        }

        h2 {
            text-align: center;
        }

        .grid {
            margin-top: 20px;
        }

    </style>

</head>

<body>

<form id="form1" runat="server">

<h2>Manage Users</h2>

<asp:GridView
    ID="gvUsers"
    runat="server"
    AutoGenerateColumns="False"
    DataKeyNames="UserID"
    CssClass="grid"
    AutoGenerateDeleteButton="True"
    OnRowDeleting="gvUsers_RowDeleting">

    <Columns>

        <asp:BoundField DataField="UserID" HeaderText="ID" />

        <asp:BoundField DataField="FullName" HeaderText="Name" />

        <asp:BoundField DataField="Email" HeaderText="Email" />

        <asp:BoundField DataField="Phone" HeaderText="Phone" />

        <asp:BoundField DataField="Address" HeaderText="Address" />

        <asp:CheckBoxField DataField="IsActive" HeaderText="Active" />

    </Columns>

</asp:GridView>

<br />

<asp:Button
    ID="btnBack"
    runat="server"
    Text="Back to Dashboard"
    PostBackUrl="~/Dashboard.aspx" />

</form>

</body>
</html>