<%@ Page Language="C#" AutoEventWireup="true" CodeBehind="ManageProducts.aspx.cs" Inherits="IADProject10.ManageProducts" %>

<!DOCTYPE html>

<html xmlns="http://www.w3.org/1999/xhtml">
<head runat="server">

    <title>Manage Products</title>

    <style>

        body{
            font-family:Arial;
            background:#f4f4f4;
            margin:0;
            padding:0;
        }

        .container{
            width:90%;
            margin:40px auto;
            background:white;
            padding:25px;
            border-radius:10px;
            box-shadow:0px 0px 10px #ccc;
        }

        h2{
            text-align:center;
        }

        .textbox{
            padding:8px;
            width:180px;
        }

        .btn{
            background:black;
            color:white;
            padding:8px 15px;
            border:none;
            border-radius:5px;
            cursor:pointer;
        }

        .grid{
            margin-top:20px;
            width:100%;
        }

    </style>

</head>

<body>

<form id="form1" runat="server">

<div class="container">

<h2>Manage Products</h2>

Product Name

<asp:TextBox
ID="txtName"
runat="server"
CssClass="textbox">
</asp:TextBox>

Price

<asp:TextBox
ID="txtPrice"
runat="server"
CssClass="textbox">
</asp:TextBox>

Stock

<asp:TextBox
ID="txtStock"
runat="server"
CssClass="textbox">
</asp:TextBox>

<asp:Button
ID="btnAdd"
runat="server"
Text="Add Product"
CssClass="btn"
OnClick="btnAdd_Click" />

<br /><br />

<asp:GridView
ID="gvProducts"
runat="server"
AutoGenerateColumns="False"
DataKeyNames="ProductID"
AutoGenerateDeleteButton="True"
OnRowDeleting="gvProducts_RowDeleting"
CssClass="grid">

<Columns>

<asp:BoundField DataField="ProductID" HeaderText="ID" />

<asp:BoundField DataField="ProductName" HeaderText="Product Name" />

<asp:BoundField DataField="Price" HeaderText="Price" />

<asp:BoundField DataField="StockQuantity" HeaderText="Stock" />

<asp:CheckBoxField DataField="IsActive" HeaderText="Active" />

</Columns>

</asp:GridView>

<br />

<asp:Button
ID="btnBack"
runat="server"
Text="Back To Dashboard"
CssClass="btn"
PostBackUrl="~/Dashboard.aspx" />

</div>

</form>

</body>
</html>